sudo: required
language: cpp
services:
  - docker
env:
  global:
    - secure: "YxHsbWRm/0GvIjtdg19NsrXfNvyJgciAe7vxXBr1uPhAAedMjnXkvichri7qg8iGGfDtunoMYskvCXES1DySmpIwsIMk+BtRiYcpIFh7ENqiG0PHUpMx0Irs6Bo8r0BSEVUm0Cas1JrJ1w+ZYW3M8oIYMX1FRpsee6cTAc4MHC4lDMLYbzS6zyT43rLxgIXQbUgNv1In+yvR3+ZrXFNieN9HLZaXu63qTcKfT0Lvzex3zM9BptVcOmx1Fc2D2TlMn1c/jHTS/zVKoL76c21TXklCbQpFnsHurWYLpas/2QqEJveRzDVk0/lwwdZRx8LIv6B9iN51aRfPhJk5eqFHI2L19FEYpgRAoVb2UAtzUEuIra1w17dFP4KjdkIylBbR1ou5J/1ClxvDmuKVStJh+KEJa/im40Yf4WJo3S2a2kQoUhRLxzxImkf6JV4tSJ5Hb+FYJyeYNIIWHHVSacAXfec3sGngiO87IFxc8MQroHJzSAJ1++neUBddZKfTmXgW2uAiYPWM2qYz+NHta7zTuK4aKoW2oto3PXMGYOTdPitnlRg9RKDCvqukrQyndmt8oi6J/ngNmZyzkQUUjShniIuHIeTARNbDD0TwWlTf/ripKtg0dcLITrgEXTf+LIYbD7scMgR8PCyEb149BrDSMrCOV/R38f6AB0xgFTlbLjg=" #DOCKER_USER
    - secure: "mvf19iiVN8o2YdkPZzmspLGz0PjDANaIrX24PkfgnTiP9JjrF1Is5qf2nwhVhAEi5ZBVH6hsDgZurEbC69L5qkGb3LQJCqciki28JgfEphQT2NNFsk2PUQmdDZRY18aj59l2UiNIKNMW/awJEB2iq86/9G50ZmOCtLAWygUMYQbIV2TKwim1C2epjDvAzWnrsDK9EIdLnbZb6kRXyH1TQp/sSUzrQn92xmUJb9aRMdmQgL8jH2ed5h7R3TDY0POzgm8jHBkFOtxhNPw/MQGXxx76McdfLXfP2PV6ibK96+RKH9DHkpcTvne9vyVgtvoU8ik6iQaTwBboFpmIkAVqxOdkAtMKJpGYTN0oBbpuorwI3K6OrG1N1yGoM81caE2G1nb2a5nnnWcDymgy1QBWrcMzOCU5zmPmXT82/stCwnCvRNojfIAA3zVBeQYu60eT+mckvMkt87u+8nv7oyFXPOfZ9ThUvEAsaZu5mSEBQSziUiuQ0CspH6akN1s8Xwcdwncy+manggiifQWmuNT+fclqjzpOCZkbg1MHuVIExUwnXQztTaNKzIsigMISe/sXSUr9IV7waV+s0lkaTFH6Z4bxdnKklS1dftwRO0bgRX4r6cyKJ4CdIP+mJEkzHeV9hJGuHAe5vR6VVEZrwj1GzzbUFrg9G8JU/iYrz0WwtFY=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - sudo git clone https://github.com/spielhuus/docker-toolchain.git /repo

script:
  - cd /repo
  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=spielhuus/toolchain
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - sudo docker build -f Dockerfile -t $REPO:$TAG .
  - sudo docker push $REPO
